manifest:
  remotes:
  - name: zmkfirmware
    url-base: https://github.com/zmkfirmware
  - name: kenyujy
    url-base: https://github.com/kenyujyp
  # Additional modules containing boards/shields/custom code can be listed here as well
  # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  # imported ec module, for EC function!!!
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-gpio-ec
      remote: kenyujy
      revision: main
    #- name: zmk-shell-cmd
    #  remote: kenyujy
    #  revision: main
  self:
    path: config

# putting extra file or folder in config will cause the board being not recognizable !!
# dummy trigger